# coding=utf8
# the above tag defines encoding for this document and is for Python 2.x compatibility

import re

regex = r"{((?:[^{}]+|{([^{}]+)})*)}"

test_str = ("#include \"StdAfx.h\"\n"
			"#include \"Resource.h\"\n"
			"#include \"PythonApplication.h\"\n"
			"#include \"../EterLib/Camera.h\"\n"
			"#include \"Locale.h\"\n"
			"#include \"../GameLib/GameLibDefines.h\"\n\n"
			"extern bool PERF_CHECKER_RENDER_GAME;\n"
			"extern D3DXCOLOR g_fSpecularColor;\n"
			"extern BOOL bVisibleNotice = true;\n"
			"extern BOOL bTestServerFlag = FALSE;\n"
			"extern int TWOHANDED_WEWAPON_ATT_SPEED_DECREASE_VALUE = 0;\n\n"
			"PyObject* appAddToClipBoard(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	char* szText;\n"
			"	if (!PyTuple_GetString(poArgs, 0, &szText))\n"
			"		return Py_BuildException();\n"
			"	CPythonApplication::Instance().addToClipBoard(szText);\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject* appEnablePerformanceTime(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	char* szMode;\n"
			"	if (!PyTuple_GetString(poArgs, 0, &szMode))\n"
			"		return Py_BuildException();\n\n"
			"	int nEnable;\n"
			"	if (!PyTuple_GetInteger(poArgs, 1, &nEnable))\n"
			"		return Py_BuildException();\n\n"
			"	bool isEnable = nEnable ? true : false;\n\n"
			"	if (strcmp(szMode, \"RENDER_GAME\")==0)\n"
			"		PERF_CHECKER_RENDER_GAME = isEnable;\n\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"/////////////////////////////////////////////////////\n\n"
			"extern BOOL HAIR_COLOR_ENABLE;\n"
			"extern BOOL USE_ARMOR_SPECULAR;\n"
			"extern BOOL USE_WEAPON_SPECULAR;\n"
			"extern BOOL SKILL_EFFECT_UPGRADE_ENABLE;\n"
			"extern BOOL RIDE_HORSE_ENABLE;\n"
			"extern double g_specularSpd;\n\n"
			"// TEXTTAIL_LIVINGTIME_CONTROL\n"
			"extern void TextTail_SetLivingTime(long livingTime);\n\n"
			"PyObject* appSetTextTailLivingTime(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	float livingTime;\n"
			"	if (!PyTuple_GetFloat(poArgs, 0, &livingTime))\n"
			"		return Py_BuildException();\n\n"
			"	TextTail_SetLivingTime(livingTime*1000);\n\n"
			"	return Py_BuildNone();\n"
			"}\n"
			"// END_OF_TEXTTAIL_LIVINGTIME_CONTROL\n\n"
			"PyObject* appSetHairColorEnable(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	int nEnable;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &nEnable))\n"
			"		return Py_BuildException();\n\n"
			"	HAIR_COLOR_ENABLE=nEnable;\n\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject* appSetArmorSpecularEnable(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	int nEnable;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &nEnable))\n"
			"		return Py_BuildException();\n\n"
			"	USE_ARMOR_SPECULAR=nEnable;\n\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject* appSetWeaponSpecularEnable(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	int nEnable;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &nEnable))\n"
			"		return Py_BuildException();\n\n"
			"	USE_WEAPON_SPECULAR=nEnable;\n\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject* appSetSkillEffectUpgradeEnable(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	int nEnable;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &nEnable))\n"
			"		return Py_BuildException();\n\n"
			"	SKILL_EFFECT_UPGRADE_ENABLE=nEnable;\n\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject* SetTwoHandedWeaponAttSpeedDecreaseValue(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	int iValue;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &iValue))\n"
			"		return Py_BuildException();\n\n"
			"	TWOHANDED_WEWAPON_ATT_SPEED_DECREASE_VALUE = iValue;\n\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject* appSetRideHorseEnable(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	int nEnable;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &nEnable))\n"
			"		return Py_BuildException();\n\n"
			"	RIDE_HORSE_ENABLE=nEnable;\n\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject* appSetCameraMaxDistance(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	float fMax;\n"
			"	if (!PyTuple_GetFloat(poArgs, 0, &fMax))\n"
			"		return Py_BuildException();\n\n"
			"	CCamera::SetCameraMaxDistance(fMax);\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject* appSetControlFP(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	_controlfp( _PC_24, _MCW_PC );\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject* appSetSpecularSpeed(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	float fSpeed;\n"
			"	if (!PyTuple_GetFloat(poArgs, 0, &fSpeed))\n"
			"		return Py_BuildException();\n\n"
			"	g_specularSpd = fSpeed;\n\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appSetMinFog(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	float fMinFog;\n"
			"	if (!PyTuple_GetFloat(poArgs, 0, &fMinFog))\n"
			"		return Py_BuildException();\n\n"
			"	CPythonApplication::Instance().SetMinFog(fMinFog);\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject* appSetFrameSkip(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	int nFrameSkip;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &nFrameSkip))\n"
			"		return Py_BuildException();\n\n"
			"	CPythonApplication::Instance().SetFrameSkip(nFrameSkip ? true : false);\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"// LOCALE\n\n"
			"PyObject* appForceSetLocale(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	char* szName;\n"
			"	if (!PyTuple_GetString(poArgs, 0, &szName))\n"
			"		return Py_BuildException();\n\n"
			"	char* szLocalePath;\n"
			"	if (!PyTuple_GetString(poArgs, 1, &szLocalePath))\n"
			"		return Py_BuildException();\n\n"
			"	LocaleService_ForceSetLocale(szName, szLocalePath);\n\n"
			"	return Py_BuildNone();\n"
			"}\n"
			"//\n"
			"bool LoadLocaleData(const char* localePath);\n\n"
			"#include \"../eterBase/tea.h\"\n\n"
			"PyObject* appLoadLocaleAddr(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	char* addrPath;\n"
			"	if (!PyTuple_GetString(poArgs, 0, &addrPath))\n"
			"		return Py_BuildException();\n\n"
			"	FILE* fp = fopen(addrPath, \"rb\");\n"
			"	if (!fp)\n"
			"		return Py_BuildException();\n\n"
			"	fseek(fp, 0, SEEK_END);\n\n"
			"	int size = ftell(fp);\n"
			"	char* enc = (char*)_alloca(size);\n"
			"	fseek(fp, 0, SEEK_SET);\n"
			"	fread(enc, size, 1, fp);\n"
			"	fclose(fp);\n\n"
			"	static const unsigned char key[16] = {\n"
			"		0x82, 0x1b, 0x34, 0xae,\n"
			"		0x12, 0x3b, 0xfb, 0x17,\n"
			"		0xd7, 0x2c, 0x39, 0xae,\n"
			"		0x41, 0x98, 0xf1, 0x63\n"
			"	};\n\n"
			"	char* buf = (char*)_alloca(size);\n"
			"	//int decSize =\n"
			"	tea_decrypt((unsigned long*)buf, (const unsigned long*)enc, (const unsigned long*)key, size);\n"
			"	unsigned int retSize = *(unsigned int*)buf;\n"
			"	char* ret = buf + sizeof(unsigned int);\n"
			"	return Py_BuildValue(\"s#\", ret, retSize);\n"
			"}\n\n"
			"PyObject* appLoadLocaleData(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	char* localePath;\n"
			"	if (!PyTuple_GetString(poArgs, 0, &localePath))\n"
			"		return Py_BuildException();\n\n"
			"	return Py_BuildValue(\"i\", LoadLocaleData(localePath));\n"
			"}\n\n"
			"PyObject* appGetLocaleName(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	return Py_BuildValue(\"s\", LocaleService_GetLocaleName());\n"
			"}\n\n"
			"PyObject* appGetLocalePath(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	//return Py_BuildValue(\"s\", LocaleService_GetLocalePath());\n"
			"	return Py_BuildValue(\"s\", CPythonApplication::Instance().GetLocaleName().c_str());\n"
			"}\n"
			"// END_OF_LOCALE\n\n"
			"PyObject* appGetDefaultCodePage(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	return Py_BuildValue(\"i\", LocaleService_GetCodePage());\n"
			"}\n\n"
			"#ifdef __VTUNE__\n\n"
			"PyObject* appGetImageInfo(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	char* szFileName;\n"
			"	if (!PyTuple_GetString(poArgs, 0, &szFileName))\n"
			"		return Py_BuildException();\n\n"
			"	return Py_BuildValue(\"iii\", 0, 0, 0);\n"
			"}\n\n"
			"#else\n\n"
			"#include <il/il.h>\n\n"
			"PyObject* appGetImageInfo(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	char* szFileName;\n"
			"	if (!PyTuple_GetString(poArgs, 0, &szFileName))\n"
			"		return Py_BuildException();\n\n"
			"	BOOL canLoad=FALSE;\n"
			"	ILuint uWidth=0;\n"
			"	ILuint uHeight=0;\n\n"
			"	ILuint uImg;\n"
			"	ilGenImages(1, &uImg);\n"
			"	ilBindImage(uImg);\n"
			"	if (ilLoad(IL_TYPE_UNKNOWN, szFileName))\n"
			"	{\n"
			"		canLoad=TRUE;\n"
			"		uWidth=ilGetInteger(IL_IMAGE_WIDTH);\n"
			"		uHeight=ilGetInteger(IL_IMAGE_HEIGHT);\n"
			"	}\n\n"
			"	ilDeleteImages(1, &uImg);\n\n"
			"	return Py_BuildValue(\"iii\", canLoad, uWidth, uHeight);\n"
			"}\n"
			"#endif\n\n"
			"#include \"../EterPack/EterPackManager.h\"\n\n"
			"PyObject* appIsExistFile(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	char* szFileName;\n"
			"	if (!PyTuple_GetString(poArgs, 0, &szFileName))\n"
			"		return Py_BuildException();\n\n"
			"	bool isExist=CEterPackManager::Instance().isExist(szFileName);\n\n"
			"	return Py_BuildValue(\"i\", isExist);\n"
			"}\n\n"
			"PyObject* appGetFileList(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	char* szFilter;\n"
			"	if (!PyTuple_GetString(poArgs, 0, &szFilter))\n"
			"		return Py_BuildException();\n\n"
			"	PyObject* poList=PyList_New(0);\n\n"
			"	WIN32_FIND_DATA wfd;\n"
			"	memset(&wfd, 0, sizeof(wfd));\n\n"
			"	HANDLE hFind = FindFirstFile(szFilter, &wfd);\n"
			"	if (hFind != INVALID_HANDLE_VALUE)\n"
			"	{\n"
			"		do\n"
			"		{\n"
			"			PyObject* poFileName=PyString_FromString(wfd.cFileName) ;\n"
			"			PyList_Append(poList, poFileName);\n"
			"		}\n"
			"		while (FindNextFile(hFind, &wfd));\n\n\n"
			"		FindClose(hFind);\n"
			"	}\n\n"
			"	return poList;\n"
			"}\n\n\n"
			"PyObject* appUpdateGame(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	CPythonApplication::Instance().UpdateGame();\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject* appRenderGame(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	CPythonApplication::Instance().RenderGame();\n"
			"	return Py_BuildNone();\n"
			"}\n\n\n\n"
			"PyObject* appSetMouseHandler(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	PyObject* poHandler;\n"
			"	if (!PyTuple_GetObject(poArgs, 0, &poHandler))\n"
			"		return Py_BuildException();\n\n"
			"	CPythonApplication::Instance().SetMouseHandler(poHandler);\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject* appCreate(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	char* szName;\n"
			"	if (!PyTuple_GetString(poArgs, 0, &szName))\n"
			"		return Py_BuildException();\n\n"
			"	int width;\n"
			"	if (!PyTuple_GetInteger(poArgs, 1, &width))\n"
			"		return Py_BuildException();\n\n"
			"	int height;\n"
			"	if (!PyTuple_GetInteger(poArgs, 2, &height))\n"
			"		return Py_BuildException();\n\n"
			"	int Windowed;\n"
			"	if (!PyTuple_GetInteger(poArgs, 3, &Windowed))\n"
			"		return Py_BuildException();\n\n"
			"	CPythonApplication& rkApp=CPythonApplication::Instance();\n"
			"	if (!rkApp.Create(poSelf, szName, width, height, Windowed))\n"
			"	{\n"
			"		//return Py_BuildNone();\n"
			"		return NULL;\n"
			"	}\n\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject* appLoop(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	CPythonApplication::Instance().Loop();\n\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject* appGetInfo(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	int nInfo;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &nInfo))\n"
			"		return Py_BuildException();\n\n"
			"	std::string stInfo;\n"
			"	CPythonApplication::Instance().GetInfo(nInfo, &stInfo);\n"
			"	return Py_BuildValue(\"s\", stInfo.c_str());\n"
			"}\n\n"
			"PyObject* appProcess(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	if (CPythonApplication::Instance().Process())\n"
			"		return Py_BuildValue(\"i\", 1);\n\n"
			"	return Py_BuildValue(\"i\", 0);\n"
			"}\n\n"
			"PyObject* appAbort(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	CPythonApplication::Instance().Abort();\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject* appExit(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	CPythonApplication::Instance().Exit();\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appSetCamera(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	float Distance;\n"
			"	if (!PyTuple_GetFloat(poArgs, 0, &Distance))\n"
			"		return Py_BuildException();\n\n"
			"	float Pitch;\n"
			"	if (!PyTuple_GetFloat(poArgs, 1, &Pitch))\n"
			"		return Py_BuildException();\n\n"
			"	float Rotation;\n"
			"	if (!PyTuple_GetFloat(poArgs, 2, &Rotation))\n"
			"		return Py_BuildException();\n\n"
			"	float fDestinationHeight;\n"
			"	if (!PyTuple_GetFloat(poArgs, 3, &fDestinationHeight))\n"
			"		return Py_BuildException();\n\n"
			"	CPythonApplication::Instance().SetCamera(Distance, Pitch, Rotation, fDestinationHeight);\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appGetCamera(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	float Distance, Pitch, Rotation, DestinationHeight;\n"
			"    CPythonApplication::Instance().GetCamera(&Distance, &Pitch, &Rotation, &DestinationHeight);\n\n"
			"	return Py_BuildValue(\"ffff\", Distance, Pitch, Rotation, DestinationHeight);\n"
			"}\n\n"
			"PyObject * appGetCameraPitch(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	return Py_BuildValue(\"f\", CPythonApplication::Instance().GetPitch());\n"
			"}\n\n"
			"PyObject * appGetCameraRotation(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	return Py_BuildValue(\"f\", CPythonApplication::Instance().GetRotation());\n"
			"}\n\n"
			"PyObject * appGetTime(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	return Py_BuildValue(\"f\", CPythonApplication::Instance().GetGlobalTime());\n"
			"}\n\n"
			"PyObject * appGetGlobalTime(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	return Py_BuildValue(\"i\", CPythonApplication::Instance().GetServerTime());\n"
			"}\n\n"
			"PyObject * appGetGlobalTimeStamp(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	return Py_BuildValue(\"i\", CPythonApplication::Instance().GetServerTimeStamp());\n"
			"}\n\n"
			"PyObject * appGetUpdateFPS(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	return Py_BuildValue(\"i\", CPythonApplication::Instance().GetUpdateFPS());\n"
			"}\n\n"
			"PyObject * appGetRenderFPS(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	return Py_BuildValue(\"i\", CPythonApplication::Instance().GetRenderFPS());\n"
			"}\n\n"
			"PyObject * appRotateCamera(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	int iDirection;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &iDirection))\n"
			"		return Py_BuildException();\n"
			"	CPythonApplication::Instance().RotateCamera(iDirection);\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appPitchCamera(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	int iDirection;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &iDirection))\n"
			"		return Py_BuildException();\n"
			"	CPythonApplication::Instance().PitchCamera(iDirection);\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appZoomCamera(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	int iDirection;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &iDirection))\n"
			"		return Py_BuildException();\n"
			"	CPythonApplication::Instance().ZoomCamera(iDirection);\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appMovieRotateCamera(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	int iDirection;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &iDirection))\n"
			"		return Py_BuildException();\n"
			"	CPythonApplication::Instance().MovieRotateCamera(iDirection);\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appMoviePitchCamera(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	int iDirection;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &iDirection))\n"
			"		return Py_BuildException();\n"
			"	CPythonApplication::Instance().MoviePitchCamera(iDirection);\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appMovieZoomCamera(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	int iDirection;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &iDirection))\n"
			"		return Py_BuildException();\n"
			"	CPythonApplication::Instance().MovieZoomCamera(iDirection);\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appMovieResetCamera(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	CPythonApplication::Instance().MovieResetCamera();\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appGetFaceSpeed(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	return Py_BuildValue(\"f\", CPythonApplication::Instance().GetFaceSpeed());\n"
			"}\n\n"
			"PyObject * appGetRenderTime(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	return Py_BuildValue(\"fi\",\n"
			"		CPythonApplication::Instance().GetAveRenderTime(),\n"
			"		CPythonApplication::Instance().GetCurRenderTime());\n"
			"}\n\n"
			"PyObject * appGetUpdateTime(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	return Py_BuildValue(\"i\", CPythonApplication::Instance().GetCurUpdateTime());\n"
			"}\n\n"
			"PyObject * appGetLoad(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	return Py_BuildValue(\"i\", CPythonApplication::Instance().GetLoad());\n"
			"}\n"
			"PyObject * appGetFaceCount(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	return Py_BuildValue(\"i\", CPythonApplication::Instance().GetFaceCount());\n"
			"}\n\n"
			"PyObject * appGetAvaiableTextureMememory(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	return Py_BuildValue(\"i\", CGraphicBase::GetAvailableTextureMemory());\n"
			"}\n\n"
			"PyObject * appSetFPS(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	int	iFPS;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &iFPS))\n"
			"		return Py_BuildException();\n\n"
			"	CPythonApplication::Instance().SetFPS(iFPS);\n\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appSetGlobalCenterPosition(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	int x;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &x))\n"
			"		return Py_BuildException();\n\n"
			"	int y;\n"
			"	if (!PyTuple_GetInteger(poArgs, 1, &y))\n"
			"		return Py_BuildException();\n\n"
			"	CPythonApplication::Instance().SetGlobalCenterPosition(x, y);\n"
			"	return Py_BuildNone();\n"
			"}\n\n\n"
			"PyObject * appSetCenterPosition(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	float fx;\n"
			"	if (!PyTuple_GetFloat(poArgs, 0, &fx))\n"
			"		return Py_BuildException();\n\n"
			"	float fy;\n"
			"	if (!PyTuple_GetFloat(poArgs, 1, &fy))\n"
			"		return Py_BuildException();\n\n"
			"	float fz;\n"
			"	if (!PyTuple_GetFloat(poArgs, 2, &fz))\n"
			"		return Py_BuildException();\n\n"
			"	CPythonApplication::Instance().SetCenterPosition(fx, -fy, fz);\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appGetCursorPosition(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	long lx, ly;\n"
			"	UI::CWindowManager& rkWndMgr=UI::CWindowManager::Instance();\n"
			"	rkWndMgr.GetMousePosition(lx, ly);\n\n"
			"	return Py_BuildValue(\"ii\", lx, ly);\n"
			"}\n\n"
			"PyObject * appRunPythonFile(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	char *szFileName;\n"
			"	if (!PyTuple_GetString(poArgs, 0, &szFileName))\n"
			"		return Py_BuildException();\n\n"
			"	bool ret = CPythonLauncher::Instance().RunFile(szFileName);\n"
			"	return Py_BuildValue(\"i\", ret);\n"
			"}\n\n"
			"PyObject * appIsPressed(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	int iKey;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &iKey))\n"
			"		return Py_BuildException();\n\n"
			"	return Py_BuildValue(\"i\", CPythonApplication::Instance().IsPressed(iKey));\n"
			"}\n\n"
			"PyObject * appSetCursor(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"/*\n"
			"	char * szName;\n"
			"	if (!PyTuple_GetString(poArgs, 0, &szName))\n"
			"		return Py_BuildException();\n\n"
			"	if (!CPythonApplication::Instance().SetHardwareCursor(szName))\n"
			"		return Py_BuildException(\"Wrong Cursor Name [%s]\", szName);\n"
			"*/\n"
			"	int iCursorNum;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &iCursorNum))\n"
			"		return Py_BuildException();\n\n"
			"	if (!CPythonApplication::Instance().SetCursorNum(iCursorNum))\n"
			"		return Py_BuildException(\"Wrong Cursor Name [%d]\", iCursorNum);\n\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appGetCursor(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	return Py_BuildValue(\"i\", CPythonApplication::Instance().GetCursorNum());\n"
			"}\n\n"
			"PyObject * appShowCursor(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	CPythonApplication::Instance().SetCursorVisible(TRUE);\n\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appHideCursor(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	CPythonApplication::Instance().SetCursorVisible(FALSE);\n\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appIsShowCursor(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	return Py_BuildValue(\"i\", TRUE == CPythonApplication::Instance().GetCursorVisible());\n"
			"}\n\n"
			"PyObject * appIsLiarCursorOn(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	return Py_BuildValue(\"i\", TRUE == CPythonApplication::Instance().GetLiarCursorOn());\n"
			"}\n\n"
			"PyObject * appSetSoftwareCursor(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	CPythonApplication::Instance().SetCursorMode(CPythonApplication::CURSOR_MODE_SOFTWARE);\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appSetHardwareCursor(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	CPythonApplication::Instance().SetCursorMode(CPythonApplication::CURSOR_MODE_HARDWARE);\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appSetConnectData(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	char * szIP;\n"
			"	if (!PyTuple_GetString(poArgs, 0, &szIP))\n"
			"		return Py_BuildException();\n\n"
			"	int	iPort;\n"
			"	if (!PyTuple_GetInteger(poArgs, 1, &iPort))\n"
			"		return Py_BuildException();\n\n"
			"	CPythonApplication::Instance().SetConnectData(szIP, iPort);\n\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appGetConnectData(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	std::string strIP;\n"
			"	int iPort;\n\n"
			"	CPythonApplication::Instance().GetConnectData(strIP, iPort);\n\n"
			"	return Py_BuildValue(\"si\", strIP.c_str(), iPort);\n"
			"}\n\n"
			"PyObject * appGetRandom(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	int from;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &from))\n"
			"		return Py_BuildException();\n\n"
			"	int	to;\n"
			"	if (!PyTuple_GetInteger(poArgs, 1, &to))\n"
			"		return Py_BuildException();\n\n"
			"	if (from > to)\n"
			"	{\n"
			"		int tmp = from;\n"
			"		from = to;\n"
			"		to = tmp;\n"
			"	}\n\n"
			"	return Py_BuildValue(\"i\", random_range(from, to));\n"
			"}\n\n"
			"PyObject * appGetRotatingDirection(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	float fSource;\n"
			"	if (!PyTuple_GetFloat(poArgs, 0, &fSource))\n"
			"		return Py_BuildException();\n"
			"	float fTarget;\n"
			"	if (!PyTuple_GetFloat(poArgs, 1, &fTarget))\n"
			"		return Py_BuildException();\n\n"
			"	return Py_BuildValue(\"i\", GetRotatingDirection(fSource, fTarget));\n"
			"}\n\n"
			"PyObject * appGetDegreeDifference(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	float fSource;\n"
			"	if (!PyTuple_GetFloat(poArgs, 0, &fSource))\n"
			"		return Py_BuildException();\n"
			"	float fTarget;\n"
			"	if (!PyTuple_GetFloat(poArgs, 1, &fTarget))\n"
			"		return Py_BuildException();\n\n"
			"	return Py_BuildValue(\"f\", GetDegreeDifference(fSource, fTarget));\n"
			"}\n\n"
			"PyObject * appSleep(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	int	iTime;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &iTime))\n"
			"		return Py_BuildException();\n\n"
			"	Sleep(iTime);\n\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appSetDefaultFontName(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	char * szFontName;\n"
			"	if (!PyTuple_GetString(poArgs, 0, &szFontName))\n"
			"		return Py_BuildException();\n\n"
			"	// DEFAULT_FONT\n"
			"	DefaultFont_SetName(szFontName);\n"
			"	// END_OF_DEFAULT_FONT\n\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appSetGuildSymbolPath(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	char * szPathName;\n"
			"	if (!PyTuple_GetString(poArgs, 0, &szPathName))\n"
			"		return Py_BuildException();\n\n"
			"	SetGuildSymbolPath(szPathName);\n\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appEnableSpecialCameraMode(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	CPythonApplication::Instance().EnableSpecialCameraMode();\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appSetCameraSpeed(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	int iPercentage;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &iPercentage))\n"
			"		return Py_BuildException();\n\n"
			"	CPythonApplication::Instance().SetCameraSpeed(iPercentage);\n\n"
			"	CCamera * pCamera = CCameraManager::Instance().GetCurrentCamera();\n"
			"	if (pCamera)\n"
			"		pCamera->SetResistance(float(iPercentage) / 100.0f);\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appIsFileExist(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	char * szFileName;\n"
			"	if (!PyTuple_GetString(poArgs, 0, &szFileName))\n"
			"		return Py_BuildException();\n\n"
			"	return Py_BuildValue(\"i\", -1 != _access(szFileName, 0));\n"
			"}\n\n"
			"PyObject * appSetCameraSetting(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	int ix;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &ix))\n"
			"		return Py_BuildException();\n"
			"	int iy;\n"
			"	if (!PyTuple_GetInteger(poArgs, 1, &iy))\n"
			"		return Py_BuildException();\n"
			"	int iz;\n"
			"	if (!PyTuple_GetInteger(poArgs, 2, &iz))\n"
			"		return Py_BuildException();\n\n"
			"	int iZoom;\n"
			"	if (!PyTuple_GetInteger(poArgs, 3, &iZoom))\n"
			"		return Py_BuildException();\n"
			"	int iRotation;\n"
			"	if (!PyTuple_GetInteger(poArgs, 4, &iRotation))\n"
			"		return Py_BuildException();\n"
			"	int iPitch;\n"
			"	if (!PyTuple_GetInteger(poArgs, 5, &iPitch))\n"
			"		return Py_BuildException();\n\n"
			"	CPythonApplication::SCameraSetting CameraSetting;\n"
			"	ZeroMemory(&CameraSetting, sizeof(CameraSetting));\n"
			"	CameraSetting.v3CenterPosition.x = float(ix);\n"
			"	CameraSetting.v3CenterPosition.y = float(iy);\n"
			"	CameraSetting.v3CenterPosition.z = float(iz);\n"
			"	CameraSetting.fZoom = float(iZoom);\n"
			"	CameraSetting.fRotation = float(iRotation);\n"
			"	CameraSetting.fPitch = float(iPitch);\n"
			"	CPythonApplication::Instance().SetEventCamera(CameraSetting);\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appSaveCameraSetting(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	char * szFileName;\n"
			"	if (!PyTuple_GetString(poArgs, 0, &szFileName))\n"
			"		return Py_BuildException();\n\n"
			"	CPythonApplication::Instance().SaveCameraSetting(szFileName);\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appLoadCameraSetting(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	char * szFileName;\n"
			"	if (!PyTuple_GetString(poArgs, 0, &szFileName))\n"
			"		return Py_BuildException();\n\n"
			"	bool bResult = CPythonApplication::Instance().LoadCameraSetting(szFileName);\n"
			"	return Py_BuildValue(\"i\", bResult);\n"
			"}\n\n"
			"PyObject * appSetDefaultCamera(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	CPythonApplication::Instance().SetDefaultCamera();\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appSetSightRange(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	int iRange;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &iRange))\n"
			"		return Py_BuildException();\n\n"
			"	CPythonApplication::Instance().SetForceSightRange(iRange);\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"extern int g_iAccumulationTime;\n\n"
			"PyObject * apptestGetAccumulationTime(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	return Py_BuildValue(\"i\", g_iAccumulationTime);\n"
			"}\n\n"
			"PyObject * apptestResetAccumulationTime(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	g_iAccumulationTime = 0;\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * apptestSetSpecularColor(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	float fr;\n"
			"	if (!PyTuple_GetFloat(poArgs, 0, &fr))\n"
			"		return Py_BuildException();\n"
			"	float fg;\n"
			"	if (!PyTuple_GetFloat(poArgs, 1, &fg))\n"
			"		return Py_BuildException();\n"
			"	float fb;\n"
			"	if (!PyTuple_GetFloat(poArgs, 2, &fb))\n"
			"		return Py_BuildException();\n"
			"	g_fSpecularColor = D3DXCOLOR(fr, fg, fb, 1.0f);\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appSetVisibleNotice(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	int iFlag;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &iFlag))\n"
			"		return Py_BuildException();\n"
			"	bVisibleNotice = iFlag;\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appIsVisibleNotice(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	return Py_BuildValue(\"i\", bVisibleNotice);\n"
			"}\n\n"
			"PyObject * appEnableTestServerFlag(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	bTestServerFlag = TRUE;\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appIsEnableTestServerFlag(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	return Py_BuildValue(\"i\", bTestServerFlag);\n"
			"}\n\n"
			"class CTextLineLoader\n"
			"{\n"
			"	public:\n"
			"		CTextLineLoader(const char * c_szFileName)\n"
			"		{\n"
			"			const VOID* pvData;\n"
			"			CMappedFile kFile;\n"
			"			if (!CEterPackManager::Instance().Get(kFile, c_szFileName, &pvData))\n"
			"				return;\n\n"
			"			m_kTextFileLoader.Bind(kFile.Size(), pvData);\n"
			"		}\n\n"
			"		DWORD GetLineCount()\n"
			"		{\n"
			"			return m_kTextFileLoader.GetLineCount();\n"
			"		}\n\n"
			"		const char * GetLine(DWORD dwIndex)\n"
			"		{\n"
			"			if (dwIndex >= GetLineCount())\n"
			"				return \"\";\n\n"
			"			return m_kTextFileLoader.GetLineString(dwIndex).c_str();\n"
			"		}\n\n"
			"	protected:\n"
			"		CMemoryTextFileLoader m_kTextFileLoader;\n"
			"};\n\n"
			"PyObject * appOpenTextFile(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	char * szFileName;\n"
			"	if (!PyTuple_GetString(poArgs, 0, &szFileName))\n"
			"		return Py_BuildException();\n\n"
			"	CTextLineLoader * pTextLineLoader = new CTextLineLoader(szFileName);\n\n"
			"	return Py_BuildValue(\"i\", (int)pTextLineLoader);\n"
			"}\n\n"
			"PyObject * appCloseTextFile(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	int iHandle;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &iHandle))\n"
			"		return Py_BuildException();\n\n"
			"	CTextLineLoader * pTextFileLoader = (CTextLineLoader *)iHandle;\n"
			"	delete pTextFileLoader;\n\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject * appGetTextFileLineCount(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	int iHandle;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &iHandle))\n"
			"		return Py_BuildException();\n\n"
			"	CTextLineLoader * pTextFileLoader = (CTextLineLoader *)iHandle;\n"
			"	return Py_BuildValue(\"i\", pTextFileLoader->GetLineCount());\n"
			"}\n\n"
			"PyObject * appGetTextFileLine(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	int iHandle;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &iHandle))\n"
			"		return Py_BuildException();\n"
			"	int iLineIndex;\n"
			"	if (!PyTuple_GetInteger(poArgs, 1, &iLineIndex))\n"
			"		return Py_BuildException();\n\n"
			"	CTextLineLoader * pTextFileLoader = (CTextLineLoader *)iHandle;\n"
			"	return Py_BuildValue(\"s\", pTextFileLoader->GetLine(iLineIndex));\n"
			"}\n\n"
			"PyObject * appSetGuildMarkPath(PyObject * poSelf, PyObject * poArgs)\n"
			"{\n"
			"	char * path;\n"
			"	if (!PyTuple_GetString(poArgs, 0, &path))\n"
			"		return Py_BuildException();\n\n"
			"    char newPath[256];\n"
			"    char * ext = strstr(path, \".tga\");\n\n"
			"    if (ext)\n"
			"    {\n"
			"		int extPos = ext - path;\n"
			"        strncpy(newPath, path, extPos);\n"
			"        newPath[extPos] = '\\0';\n"
			"    }\n"
			"    else\n"
			"        strncpy(newPath, path, sizeof(newPath)-1);\n\n"
			"	CGuildMarkManager::Instance().SetMarkPathPrefix(newPath);\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject* appIsDevStage(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	int nIsDevelopmentStage = 0;\n"
			"#if defined(LOCALE_SERVICE_STAGE_DEVELOPMENT)\n"
			"	nIsDevelopmentStage = 1;\n"
			"#endif\n"
			"	return Py_BuildValue(\"i\", nIsDevelopmentStage);\n"
			"}\n\n"
			"PyObject* appIsTestStage(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	int nIsTestStage = 0;\n"
			"#if defined(LOCALE_SERVICE_STAGE_TEST)\n"
			"	nIsTestStage = 1;\n"
			"#endif\n"
			"	return Py_BuildValue(\"i\", nIsTestStage);\n"
			"}\n\n"
			"PyObject* appIsLiveStage(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	int nIsLiveStage = 0;\n"
			"#if !defined(LOCALE_SERVICE_STAGE_TEST) && !defined(LOCALE_SERVICE_STAGE_DEVELOPMENT)\n"
			"	nIsLiveStage = 1;\n"
			"#endif\n"
			"	return Py_BuildValue(\"i\", nIsLiveStage);\n"
			"}\n\n"
			"PyObject* appLogoOpen(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	char* szName;\n"
			"	if (!PyTuple_GetString(poArgs, 0, &szName))\n"
			"		return Py_BuildException();\n\n"
			"	int nIsSuccess = 1; //CPythonApplication::Instance().OnLogoOpen(szName);\n"
			"	CMovieMan::Instance().PlayLogo(szName);\n\n"
			"	return Py_BuildValue(\"i\", nIsSuccess);\n"
			"}\n\n"
			"PyObject* appLogoUpdate(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	int nIsRun = 0; //CPythonApplication::Instance().OnLogoUpdate();\n"
			"	return Py_BuildValue(\"i\", nIsRun);\n"
			"}\n\n"
			"#ifdef ENABLE_MAP_LOCATION_APP_NAME\n"
			"PyObject* appSetText(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	char* szName;\n"
			"	if (!PyTuple_GetString(poArgs, 0, &szName))\n"
			"		return Py_BuildException();\n\n"
			"	CPythonApplication& rkApp = CPythonApplication::Instance();\n"
			"	rkApp.SetText(szName);\n"
			"	return Py_BuildNone();\n"
			"}\n"
			"#endif\n\n"
			"PyObject* appLogoRender(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	//CPythonApplication::Instance().OnLogoRender();\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"PyObject* appLogoClose(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	//CPythonApplication::Instance().OnLogoClose();\n"
			"	return Py_BuildNone();\n"
			"}\n\n"
			"#ifdef ENABLE_MULTI_LANGUAGE_SYSTEM\n"
			"PyObject* appSetLocale(PyObject* poSelf, PyObject* poArgs)\n"
			"{\n"
			"	int iCodePage;\n"
			"	if (!PyTuple_GetInteger(poArgs, 0, &iCodePage))\n"
			"		return Py_BuildException();\n\n"
			"	char* szLocale;\n"
			"	if (!PyTuple_GetString(poArgs, 1, &szLocale))\n"
			"		return Py_BuildException();\n\n"
			"	return Py_BuildValue(\"i\", LocaleService_SaveLocale(iCodePage, szLocale));\n"
			"}\n"
			"#endif\n\n"
			"void initapp()\n"
			"{\n"
			"	static PyMethodDef s_methods[] =\n"
			"	{\n"
			"		{ \"IsDevStage\",					appIsDevStage,					METH_VARARGS },\n"
			"		{ \"IsTestStage\",				appIsTestStage,					METH_VARARGS },\n"
			"		{ \"IsLiveStage\",				appIsLiveStage,					METH_VARARGS },\n\n"
			"		// TEXTTAIL_LIVINGTIME_CONTROL\n"
			"		{ \"SetTextTailLivingTime\",		appSetTextTailLivingTime,		METH_VARARGS },\n"
			"		// END_OF_TEXTTAIL_LIVINGTIME_CONTROL\n\n"
			"		{ \"EnablePerformanceTime\",		appEnablePerformanceTime,		METH_VARARGS },\n"
			"		{ \"SetHairColorEnable\",			appSetHairColorEnable,			METH_VARARGS },\n\n"
			"		{ \"SetArmorSpecularEnable\",		appSetArmorSpecularEnable,		METH_VARARGS },\n"
			"		{ \"SetWeaponSpecularEnable\",	appSetWeaponSpecularEnable,		METH_VARARGS },\n"
			"		{ \"SetSkillEffectUpgradeEnable\",appSetSkillEffectUpgradeEnable,	METH_VARARGS },\n"
			"		{ \"SetTwoHandedWeaponAttSpeedDecreaseValue\", SetTwoHandedWeaponAttSpeedDecreaseValue, METH_VARARGS },\n"
			"		{ \"SetRideHorseEnable\",			appSetRideHorseEnable,			METH_VARARGS },\n\n"
			"		{ \"SetCameraMaxDistance\",		appSetCameraMaxDistance,		METH_VARARGS },\n"
			"		{ \"SetMinFog\",					appSetMinFog,					METH_VARARGS },\n"
			"		{ \"SetFrameSkip\",				appSetFrameSkip,				METH_VARARGS },\n"
			"		{ \"GetImageInfo\",				appGetImageInfo,				METH_VARARGS },\n"
			"		{ \"GetInfo\",					appGetInfo,						METH_VARARGS },\n"
			"		{ \"UpdateGame\",					appUpdateGame,					METH_VARARGS },\n"
			"		{ \"RenderGame\",					appRenderGame,					METH_VARARGS },\n"
			"		{ \"Loop\",						appLoop,						METH_VARARGS },\n"
			"		{ \"Create\",						appCreate,						METH_VARARGS },\n"
			"		{ \"Process\",					appProcess,						METH_VARARGS },\n"
			"		{ \"Exit\",						appExit,						METH_VARARGS },\n"
			"		{ \"Abort\",						appAbort,						METH_VARARGS },\n"
			"		{ \"SetMouseHandler\",			appSetMouseHandler,				METH_VARARGS },\n"
			"		{ \"IsExistFile\",				appIsExistFile,					METH_VARARGS },\n"
			"		{ \"GetFileList\",				appGetFileList,					METH_VARARGS },\n\n"
			"		{ \"SetCamera\",					appSetCamera,					METH_VARARGS },\n"
			"		{ \"GetCamera\",					appGetCamera,					METH_VARARGS },\n"
			"		{ \"GetCameraPitch\",				appGetCameraPitch,				METH_VARARGS },\n"
			"		{ \"GetCameraRotation\",			appGetCameraRotation,			METH_VARARGS },\n"
			"		{ \"GetTime\",					appGetTime,						METH_VARARGS },\n"
			"		{ \"GetGlobalTime\",				appGetGlobalTime,				METH_VARARGS },\n"
			"		{ \"GetGlobalTimeStamp\",			appGetGlobalTimeStamp,			METH_VARARGS },\n"
			"		{ \"GetUpdateFPS\",				appGetUpdateFPS,				METH_VARARGS },\n"
			"		{ \"GetRenderFPS\",				appGetRenderFPS,				METH_VARARGS },\n"
			"		{ \"RotateCamera\",				appRotateCamera,				METH_VARARGS },\n"
			"		{ \"PitchCamera\",				appPitchCamera,					METH_VARARGS },\n"
			"		{ \"ZoomCamera\",					appZoomCamera,					METH_VARARGS },\n"
			"		{ \"MovieRotateCamera\",			appMovieRotateCamera,			METH_VARARGS },\n"
			"		{ \"MoviePitchCamera\",			appMoviePitchCamera,			METH_VARARGS },\n"
			"		{ \"MovieZoomCamera\",			appMovieZoomCamera,				METH_VARARGS },\n"
			"		{ \"MovieResetCamera\",			appMovieResetCamera,			METH_VARARGS },\n\n"
			"		{ \"GetAvailableTextureMemory\",	appGetAvaiableTextureMememory,	METH_VARARGS },\n"
			"		{ \"GetRenderTime\",				appGetRenderTime,				METH_VARARGS },\n"
			"		{ \"GetUpdateTime\",				appGetUpdateTime,				METH_VARARGS },\n"
			"		{ \"GetLoad\",					appGetLoad,						METH_VARARGS },\n"
			"		{ \"GetFaceSpeed\",				appGetFaceSpeed,				METH_VARARGS },\n"
			"		{ \"GetFaceCount\",				appGetFaceCount,				METH_VARARGS },\n"
			"		{ \"SetFPS\",						appSetFPS,						METH_VARARGS },\n"
			"		{ \"SetGlobalCenterPosition\",	appSetGlobalCenterPosition,		METH_VARARGS },\n"
			"		{ \"SetCenterPosition\",			appSetCenterPosition,			METH_VARARGS },\n"
			"		{ \"GetCursorPosition\",			appGetCursorPosition,			METH_VARARGS },\n\n"
			"		{ \"GetRandom\",					appGetRandom,					METH_VARARGS },\n"
			"		{ \"RunPythonFile\",				appRunPythonFile,				METH_VARARGS },\n"
			"		{ \"IsPressed\",					appIsPressed,					METH_VARARGS },\n"
			"		{ \"SetCursor\",					appSetCursor,					METH_VARARGS },\n"
			"		{ \"GetCursor\",					appGetCursor,					METH_VARARGS },\n"
			"		{ \"ShowCursor\",					appShowCursor,					METH_VARARGS },\n"
			"		{ \"HideCursor\",					appHideCursor,					METH_VARARGS },\n"
			"		{ \"IsShowCursor\",				appIsShowCursor,				METH_VARARGS },\n"
			"		{ \"IsLiarCursorOn\",				appIsLiarCursorOn,				METH_VARARGS },\n"
			"		{ \"SetSoftwareCursor\",			appSetSoftwareCursor,			METH_VARARGS },\n"
			"		{ \"SetHardwareCursor\",			appSetHardwareCursor,			METH_VARARGS },\n\n"
			"#ifdef ENABLE_MAP_LOCATION_APP_NAME\n"
			"		{ \"SetText\",					appSetText,						METH_VARARGS },\n"
			"#endif\n\n"
			"		{ \"SetConnectData\",				appSetConnectData,				METH_VARARGS },\n"
			"		{ \"GetConnectData\",				appGetConnectData,				METH_VARARGS },\n\n"
			"		{ \"GetRotatingDirection\",		appGetRotatingDirection,		METH_VARARGS },\n"
			"		{ \"GetDegreeDifference\",		appGetDegreeDifference,			METH_VARARGS },\n"
			"		{ \"Sleep\",						appSleep,						METH_VARARGS },\n"
			"		{ \"SetDefaultFontName\",			appSetDefaultFontName,			METH_VARARGS },\n"
			"		{ \"SetGuildSymbolPath\",			appSetGuildSymbolPath,			METH_VARARGS },\n\n"
			"		{ \"EnableSpecialCameraMode\",	appEnableSpecialCameraMode,		METH_VARARGS },\n"
			"		{ \"SetCameraSpeed\",				appSetCameraSpeed,				METH_VARARGS },\n\n"
			"		{ \"SaveCameraSetting\",			appSaveCameraSetting,			METH_VARARGS },\n"
			"		{ \"LoadCameraSetting\",			appLoadCameraSetting,			METH_VARARGS },\n"
			"		{ \"SetDefaultCamera\",			appSetDefaultCamera,			METH_VARARGS },\n"
			"		{ \"SetCameraSetting\",			appSetCameraSetting,			METH_VARARGS },\n\n"
			"		{ \"SetSightRange\",				appSetSightRange,				METH_VARARGS },\n\n"
			"		{ \"IsFileExist\",				appIsFileExist,					METH_VARARGS },\n"
			"		{ \"OpenTextFile\",				appOpenTextFile,				METH_VARARGS },\n"
			"		{ \"CloseTextFile\",				appCloseTextFile,				METH_VARARGS },\n"
			"		{ \"GetTextFileLineCount\",		appGetTextFileLineCount,		METH_VARARGS },\n"
			"		{ \"GetTextFileLine\",			appGetTextFileLine,				METH_VARARGS },\n\n"
			"		// LOCALE\n"
			"		{ \"GetLocaleName\",				appGetLocaleName,				METH_VARARGS },\n"
			"		{ \"GetLocalePath\",				appGetLocalePath,				METH_VARARGS },\n"
			"		{ \"ForceSetLocale\",				appForceSetLocale,				METH_VARARGS },\n"
			"		// END_OF_LOCALE\n\n"
			"		// CHEONMA\n"
			"		{ \"LoadLocaleAddr\",				appLoadLocaleAddr,				METH_VARARGS },\n"
			"		{ \"LoadLocaleData\",				appLoadLocaleData,				METH_VARARGS },\n"
			"		// END_OF_CHEONMA\n\n"
			"		{ \"GetDefaultCodePage\",			appGetDefaultCodePage,			METH_VARARGS },\n"
			"		{ \"SetControlFP\",				appSetControlFP,				METH_VARARGS },\n"
			"		{ \"SetSpecularSpeed\",			appSetSpecularSpeed,			METH_VARARGS },\n\n"
			"		{ \"testGetAccumulationTime\",	apptestGetAccumulationTime,		METH_VARARGS },\n"
			"		{ \"testResetAccumulationTime\",	apptestResetAccumulationTime,	METH_VARARGS },\n"
			"		{ \"testSetSpecularColor\",		apptestSetSpecularColor,		METH_VARARGS },\n\n"
			"		{ \"SetVisibleNotice\",			appSetVisibleNotice,			METH_VARARGS },\n"
			"		{ \"IsVisibleNotice\",			appIsVisibleNotice,				METH_VARARGS },\n"
			"		{ \"EnableTestServerFlag\",		appEnableTestServerFlag,		METH_VARARGS },\n"
			"		{ \"IsEnableTestServerFlag\",		appIsEnableTestServerFlag,		METH_VARARGS },\n\n"
			"		{ \"SetGuildMarkPath\",			appSetGuildMarkPath,			METH_VARARGS },\n\n"
			"		{ \"OnLogoUpdate\",				appLogoUpdate,					METH_VARARGS },\n"
			"		{ \"OnLogoRender\",				appLogoRender,					METH_VARARGS },\n"
			"		{ \"OnLogoOpen\",					appLogoOpen,					METH_VARARGS },\n"
			"		{ \"OnLogoClose\",				appLogoClose,					METH_VARARGS },\n\n"
			"		{ \"AddToClipBoard\",				appAddToClipBoard,				METH_VARARGS },\n\n"
			"#ifdef ENABLE_MULTI_LANGUAGE_SYSTEM\n"
			"		{ \"SetLocale\",					appSetLocale,					METH_VARARGS },\n"
			"#endif\n\n"
			"		{ NULL, NULL },\n"
			"	};\n\n"
			"	PyObject * poModule = Py_InitModule(\"app\", s_methods);\n\n"
			"	PyModule_AddIntConstant(poModule, \"INFO_ITEM\",		CPythonApplication::INFO_ITEM);\n"
			"	PyModule_AddIntConstant(poModule, \"INFO_ACTOR\",		CPythonApplication::INFO_ACTOR);\n"
			"	PyModule_AddIntConstant(poModule, \"INFO_EFFECT\",	CPythonApplication::INFO_EFFECT);\n"
			"	PyModule_AddIntConstant(poModule, \"INFO_TEXTTAIL\",	CPythonApplication::INFO_TEXTTAIL);\n\n"
			"	PyModule_AddIntConstant(poModule, \"DEGREE_DIRECTION_SAME\",		DEGREE_DIRECTION_SAME);\n"
			"	PyModule_AddIntConstant(poModule, \"DEGREE_DIRECTION_RIGHT\",		DEGREE_DIRECTION_RIGHT);\n"
			"	PyModule_AddIntConstant(poModule, \"DEGREE_DIRECTION_LEFT\",		DEGREE_DIRECTION_LEFT);\n\n"
			"	PyModule_AddIntConstant(poModule, \"VK_LEFT\",	     VK_LEFT);\n"
			"	PyModule_AddIntConstant(poModule, \"VK_RIGHT\",	     VK_RIGHT);\n"
			"	PyModule_AddIntConstant(poModule, \"VK_UP\",		     VK_UP);\n"
			"	PyModule_AddIntConstant(poModule, \"VK_DOWN\",	     VK_DOWN);\n"
			"	PyModule_AddIntConstant(poModule, \"VK_HOME\",	     VK_HOME);\n"
			"	PyModule_AddIntConstant(poModule, \"VK_END\",          VK_END);\n"
			"	PyModule_AddIntConstant(poModule, \"VK_DELETE\",	     VK_DELETE);\n\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_ESCAPE\",      DIK_ESCAPE);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_ESC\",         DIK_ESCAPE);	// ���Ǹ� ����\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_1\",           DIK_1);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_2\",           DIK_2);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_3\",           DIK_3);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_4\",           DIK_4);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_5\",           DIK_5);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_6\",           DIK_6);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_7\",           DIK_7);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_8\",           DIK_8);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_9\",           DIK_9);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_0\",           DIK_0);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_MINUS\",       DIK_MINUS);        /* - on main keyboard */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_EQUALS\",      DIK_EQUALS);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_BACK\",        DIK_BACK);           /* backspace */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_TAB\",         DIK_TAB);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_Q\",           DIK_Q);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_W\",           DIK_W);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_E\",           DIK_E);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_R\",           DIK_R);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_T\",           DIK_T);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_Y\",           DIK_Y);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_U\",           DIK_U);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_I\",           DIK_I);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_O\",           DIK_O);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_P\",           DIK_P);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_LBRACKET\",    DIK_LBRACKET);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_RBRACKET\",    DIK_RBRACKET);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_RETURN\",      DIK_RETURN);         /* Enter on main keyboard */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_LCONTROL\",    DIK_LCONTROL);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_A\",           DIK_A);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_S\",           DIK_S);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_D\",           DIK_D);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_F\",           DIK_F);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_G\",           DIK_G);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_H\",           DIK_H);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_J\",           DIK_J);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_K\",           DIK_K);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_L\",           DIK_L);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_SEMICOLON\",   DIK_SEMICOLON);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_APOSTROPHE\",  DIK_APOSTROPHE);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_GRAVE\",       DIK_GRAVE);          /* accent grave */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_LSHIFT\",      DIK_LSHIFT);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_BACKSLASH\",   DIK_BACKSLASH);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_Z\",           DIK_Z);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_X\",           DIK_X);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_C\",           DIK_C);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_V\",           DIK_V);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_B\",           DIK_B);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_N\",           DIK_N);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_M\",           DIK_M);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_COMMA\",       DIK_COMMA);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_PERIOD\",      DIK_PERIOD);         /* . on main keyboard */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_SLASH\",       DIK_SLASH);          /* / on main keyboard */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_RSHIFT\",      DIK_RSHIFT);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_MULTIPLY\",    DIK_MULTIPLY);       /* * on numeric keypad */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_LALT\",        DIK_LMENU);          /* left Alt */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_SPACE\",       DIK_SPACE);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_CAPITAL\",     DIK_CAPITAL);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_F1\",          DIK_F1);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_F2\",          DIK_F2);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_F3\",          DIK_F3);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_F4\",          DIK_F4);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_F5\",          DIK_F5);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_F6\",          DIK_F6);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_F7\",          DIK_F7);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_F8\",          DIK_F8);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_F9\",          DIK_F9);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_F10\",         DIK_F10);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_NUMLOCK\",     DIK_NUMLOCK);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_SCROLL\",      DIK_SCROLL);         /* Scroll Lock */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_NUMPAD7\",     DIK_NUMPAD7);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_NUMPAD8\",     DIK_NUMPAD8);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_NUMPAD9\",     DIK_NUMPAD9);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_SUBTRACT\",    DIK_SUBTRACT);       /* - on numeric keypad */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_NUMPAD4\",     DIK_NUMPAD4);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_NUMPAD5\",     DIK_NUMPAD5);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_NUMPAD6\",     DIK_NUMPAD6);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_ADD\",         DIK_ADD);            /* + on numeric keypad */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_NUMPAD1\",     DIK_NUMPAD1);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_NUMPAD2\",     DIK_NUMPAD2);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_NUMPAD3\",     DIK_NUMPAD3);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_NUMPAD0\",     DIK_NUMPAD0);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_DECIMAL\",     DIK_DECIMAL);        /* . on numeric keypad */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_F11\",         DIK_F11);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_F12\",         DIK_F12);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_NEXTTRACK\",   DIK_NEXTTRACK);      /* Next Track */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_NUMPADENTER\", DIK_NUMPADENTER);    /* Enter on numeric keypad */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_RCONTROL\",    DIK_RCONTROL);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_MUTE\",        DIK_MUTE);           /* Mute */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_CALCULATOR\",  DIK_CALCULATOR);     /* Calculator */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_PLAYPAUSE\",   DIK_PLAYPAUSE);      /* Play / Pause */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_MEDIASTOP\",   DIK_MEDIASTOP);      /* Media Stop */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_VOLUMEDOWN\",  DIK_VOLUMEDOWN);     /* Volume - */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_VOLUMEUP\",    DIK_VOLUMEUP);       /* Volume + */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_WEBHOME\",     DIK_WEBHOME);        /* Web home */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_NUMPADCOMMA\", DIK_NUMPADCOMMA);    /* , on numeric keypad (NEC PC98) */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_DIVIDE\",      DIK_DIVIDE);         /* / on numeric keypad */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_SYSRQ\",       DIK_SYSRQ);\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_RALT\",        DIK_RMENU);          /* right Alt */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_PAUSE\",       DIK_PAUSE);          /* Pause */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_HOME\",        DIK_HOME);           /* Home on arrow keypad */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_UP\",          DIK_UP);             /* UpArrow on arrow keypad */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_PGUP\",        DIK_PRIOR);          /* PgUp on arrow keypad */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_LEFT\",        DIK_LEFT);           /* LeftArrow on arrow keypad */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_RIGHT\",       DIK_RIGHT);          /* RightArrow on arrow keypad */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_END\",         DIK_END);            /* End on arrow keypad */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_DOWN\",        DIK_DOWN);           /* DownArrow on arrow keypad */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_PGDN\",        DIK_NEXT);           /* PgDn on arrow keypad */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_INSERT\",      DIK_INSERT);         /* Insert on arrow keypad */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_DELETE\",      DIK_DELETE);         /* Delete on arrow keypad */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_LWIN\",        DIK_LWIN);           /* Left Windows key */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_RWIN\",        DIK_RWIN);           /* Right Windows key */\n"
			"	PyModule_AddIntConstant(poModule, \"DIK_APPS\",        DIK_APPS);           /* AppMenu key */\n\n"
			"	// Cursor\n"
			"	PyModule_AddIntConstant(poModule, \"NORMAL\",			CPythonApplication::CURSOR_SHAPE_NORMAL);\n"
			"	PyModule_AddIntConstant(poModule, \"ATTACK\",			CPythonApplication::CURSOR_SHAPE_ATTACK);\n"
			"	PyModule_AddIntConstant(poModule, \"TARGET\",			CPythonApplication::CURSOR_SHAPE_TARGET);\n"
			"	PyModule_AddIntConstant(poModule, \"TALK\",			CPythonApplication::CURSOR_SHAPE_TALK);\n"
			"	PyModule_AddIntConstant(poModule, \"CANT_GO\",		CPythonApplication::CURSOR_SHAPE_CANT_GO);\n"
			"	PyModule_AddIntConstant(poModule, \"PICK\",			CPythonApplication::CURSOR_SHAPE_PICK);\n\n"
			"	PyModule_AddIntConstant(poModule, \"DOOR\",			CPythonApplication::CURSOR_SHAPE_DOOR);\n"
			"	PyModule_AddIntConstant(poModule, \"CHAIR\",			CPythonApplication::CURSOR_SHAPE_CHAIR);\n"
			"	PyModule_AddIntConstant(poModule, \"MAGIC\",			CPythonApplication::CURSOR_SHAPE_MAGIC);\n"
			"	PyModule_AddIntConstant(poModule, \"BUY\",			CPythonApplication::CURSOR_SHAPE_BUY);\n"
			"	PyModule_AddIntConstant(poModule, \"SELL\",			CPythonApplication::CURSOR_SHAPE_SELL);\n\n"
			"	PyModule_AddIntConstant(poModule, \"CAMERA_ROTATE\",	CPythonApplication::CURSOR_SHAPE_CAMERA_ROTATE);\n"
			"	PyModule_AddIntConstant(poModule, \"HSIZE\",			CPythonApplication::CURSOR_SHAPE_HSIZE);\n"
			"	PyModule_AddIntConstant(poModule, \"VSIZE\",			CPythonApplication::CURSOR_SHAPE_VSIZE);\n"
			"	PyModule_AddIntConstant(poModule, \"HVSIZE\",			CPythonApplication::CURSOR_SHAPE_HVSIZE);\n\n"
			"	PyModule_AddIntConstant(poModule, \"CAMERA_TO_POSITIVE\",		CPythonApplication::CAMERA_TO_POSITIVE);\n"
			"	PyModule_AddIntConstant(poModule, \"CAMERA_TO_NEGATIVE\",		CPythonApplication::CAMERA_TO_NEGITIVE);\n"
			"	PyModule_AddIntConstant(poModule, \"CAMERA_STOP\",			CPythonApplication::CAMERA_STOP);\n"
			"	PyModule_AddStringConstant(poModule, \"GM_MARKER\", GM_SPECIAL_CHAR);\n\n"
			"#ifdef ENABLE_COSTUME_SYSTEM\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_COSTUME_SYSTEM\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_COSTUME_SYSTEM\",	0);\n"
			"#endif\n"
			"#ifdef ENABLE_SWITCHBOT\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_SWITCHBOT\", 1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_SWITCHBOT\", 0);\n"
			"#endif\n"
			"#ifdef ENABLE_WHISPER_RENEWAL\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_WHISPER_RENEWAL\", 1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_WHISPER_RENEWAL\", 0);\n"
			"#endif\n\n"
			"#if defined(__CHANNEL_STATUS_UPDATE__)\n"
			"	PyModule_AddIntConstant(poModule, \"__CHANNEL_STATUS_UPDATE__\", true);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"__CHANNEL_STATUS_UPDATE__\", false);\n"
			"#endif\n\n"
			"#if defined(QUEST_BY_NAME)\n"
			"	PyModule_AddIntConstant(poModule, \"QUEST_BY_NAME\", 1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"QUEST_BY_NAME\", 0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_ITEMSHOP\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_ITEMSHOP\", 1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_ITEMSHOP\", 0);\n"
			"#endif\n"
			"	\n"
			"#ifdef ENABLE_ENERGY_SYSTEM\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_ENERGY_SYSTEM\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_ENERGY_SYSTEM\",	0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_DRAGON_SOUL_SYSTEM\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_DRAGON_SOUL_SYSTEM\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_DRAGON_SOUL_SYSTEM\",	0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_NEW_EQUIPMENT_SYSTEM\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_NEW_EQUIPMENT_SYSTEM\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_NEW_EQUIPMENT_SYSTEM\",	0);\n"
			"#endif\n"
			"	\n\n"
			"#ifdef ENABLE_NEW_EQUIPMENT_SYSTEM\n"
			"		PyModule_AddIntConstant(poModule, \"ENABLE_MULTI_LANGUAGE_SYSTEM\", 1);\n"
			"		PyModule_AddIntConstant(poModule, \"LOCALE_YMIR\", CPythonApplication::LOCALE_YMIR);\n"
			"		PyModule_AddIntConstant(poModule, \"LOCALE_EN\", CPythonApplication::LOCALE_EN);\n"
			"		PyModule_AddIntConstant(poModule, \"LOCALE_FR\", CPythonApplication::LOCALE_FR);\n"
			"		PyModule_AddIntConstant(poModule, \"LOCALE_DE\", CPythonApplication::LOCALE_DE);\n"
			"		PyModule_AddIntConstant(poModule, \"LOCALE_RO\", CPythonApplication::LOCALE_RO);\n"
			"		PyModule_AddIntConstant(poModule, \"LOCALE_IT\", CPythonApplication::LOCALE_IT);\n"
			"		PyModule_AddIntConstant(poModule, \"LOCALE_PL\", CPythonApplication::LOCALE_PL);\n"
			"		PyModule_AddIntConstant(poModule, \"LOCALE_TR\", CPythonApplication::LOCALE_TR);\n"
			"		PyModule_AddIntConstant(poModule, \"LOCALE_PT\", CPythonApplication::LOCALE_PT);\n"
			"		PyModule_AddIntConstant(poModule, \"LOCALE_HU\", CPythonApplication::LOCALE_HU);\n"
			"		PyModule_AddIntConstant(poModule, \"LOCALE_ES\", CPythonApplication::LOCALE_ES);\n"
			"		PyModule_AddIntConstant(poModule, \"LOCALE_MAX_NUM\", CPythonApplication::LOCALE_MAX_NUM);\n"
			"#else\n"
			"		PyModule_AddIntConstant(poModule, \"ENABLE_MULTI_LANGUAGE_SYSTEM\", 0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_QUIVER_SYSTEM\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_QUIVER_SYSTEM\", 1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_QUIVER_SYSTEM\", 0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_SOULBIND_SYSTEM\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_SOULBIND_SYSTEM\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_SOULBIND_SYSTEM\",	0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_PLAYER_PER_ACCOUNT5\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_PLAYER_PER_ACCOUNT5\",	1);\n"
			"	PyModule_AddIntConstant(poModule, \"PLAYER_PER_ACCOUNT\",	PLAYER_PER_ACCOUNT5);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_PLAYER_PER_ACCOUNT5\",	0);\n"
			"	PyModule_AddIntConstant(poModule, \"PLAYER_PER_ACCOUNT\",	PLAYER_PER_ACCOUNT4);\n"
			"#endif\n\n"
			"#ifdef ENABLE_BIOLOG_SYSTEM\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_BIOLOG_SYSTEM\", 1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_BIOLOG_SYSTEM\", 0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_MAP_LOCATION_APP_NAME\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_MAP_LOCATION_APP_NAME\", 1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_MAP_LOCATION_APP_NAME\", 0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_WOLFMAN_CHARACTER\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_WOLFMAN_CHARACTER\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_WOLFMAN_CHARACTER\",	0);\n"
			"#endif\n\n"
			"#if defined(SKILL_COOLTIME_UPDATE)\n"
			"	PyModule_AddIntConstant(poModule, \"SKILL_COOLTIME_UPDATE\", true);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"SKILL_COOLTIME_UPDATE\", false);\n"
			"#endif\n"
			"	\n"
			"#if defined(ENABLE_CACHE_MP)\n"
			"		PyModule_AddIntConstant(poModule, \"ENABLE_CACHE_MP\", true);\n"
			"#else\n"
			"		PyModule_AddIntConstant(poModule, \"ENABLE_CACHE_MP\", false);\n"
			"#endif\n\n"
			"#ifdef ENABLE_LEVEL_IN_TRADE\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_LEVEL_IN_TRADE\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_LEVEL_IN_TRADE\",	0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_SPECIAL_STORAGE\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_SPECIAL_STORAGE\", 1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_SPECIAL_STORAGE\", 0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_678TH_SKILL\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_678TH_SKILL\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_678TH_SKILL\",	0);\n"
			"#endif\n\n"
			"#ifdef LOGIN_COUNT_DOWN_UI_MODIFY\n"
			"	PyModule_AddIntConstant(poModule, \"LOGIN_COUNT_DOWN_UI_MODIFY\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"LOGIN_COUNT_DOWN_UI_MODIFY\",	0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_MOUNT_COSTUME_SYSTEM\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_MOUNT_COSTUME_SYSTEM\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_MOUNT_COSTUME_SYSTEM\",	0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_ACCE_COSTUME_SYSTEM\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_ACCE_COSTUME_SYSTEM\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_ACCE_COSTUME_SYSTEM\",	0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_SORT_INVEN\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_SORT_INVEN\", true);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_SORT_INVEN\", false);\n"
			"#endif\n\n"
			"#ifdef ENABLE_ACCE_SYSTEM\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_ACCE_SYSTEM\", 1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_ACCE_SYSTEM\", 0);\n"
			"#endif\n"
			"#ifdef ENABLE_ENVIRONMENT_EFFECT_OPTION\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_ENVIRONMENT_EFFECT_OPTION\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_ENVIRONMENT_EFFECT_OPTION\",	0);\n"
			"#endif\n\n"
			"#ifdef WJ_SHOW_MOB_INFO\n"
			"	PyModule_AddIntConstant(poModule, \"WJ_SHOW_MOB_INFO\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"WJ_SHOW_MOB_INFO\",	0);\n"
			"#endif\n"
			"#ifdef ENABLE_SKILL_COLOR_SYSTEM\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_SKILL_COLOR_SYSTEM\", 1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_SKILL_COLOR_SYSTEM\", 0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_CONFIG_MODULE\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_CONFIG_MODULE\", 1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_CONFIG_MODULE\", 0);\n"
			"#endif\n"
			"#ifdef NEW_SELECT_CHARACTER\n"
			"	PyModule_AddIntConstant(poModule, \"NEW_SELECT_CHARACTER\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"NEW_SELECT_CHARACTER\",	0);\n"
			"#endif\n\n"
			"#ifdef ELEMENT_TARGET\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_VIEW_ELEMENT\", 1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_VIEW_ELEMENT\", 0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_GROWTH_PET_SYSTEM\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_GROWTH_PET_SYSTEM\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_GROWTH_PET_SYSTEM\",	0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_AUTO_SYSTEM\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_AUTO_SYSTEM\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_AUTO_SYSTEM\",	0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_MONSTER_CARD\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_MONSTER_CARD\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_MONSTER_CARD\",	0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_HELP_RENEWAL\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_HELP_RENEWAL\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_HELP_RENEWAL\",	0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_MAGIC_REDUCTION_SYSTEM\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_MAGIC_REDUCTION_SYSTEM\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_MAGIC_REDUCTION_SYSTEM\",	0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_DICE_SYSTEM\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_DICE_SYSTEM\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_DICE_SYSTEM\",	0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_CHANGE_LOOK_SYSTEM\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_CHANGE_LOOK_SYSTEM\", 1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_CHANGE_LOOK_SYSTEM\", 0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_CHEQUE_SYSTEM\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_CHEQUE_SYSTEM\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_CHEQUE_SYSTEM\",	0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_EXTEND_INVEN_SYSTEM\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_EXTEND_INVEN_SYSTEM\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_EXTEND_INVEN_SYSTEM\",	0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_SHINING_SYSTEM\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_SHINING_SYSTEM\", 1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_SHINING_SYSTEM\", 0);\n"
			"#endif\n"
			"	\n\n"
			"#ifdef ENABLE_WEAPON_COSTUME_SYSTEM\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_WEAPON_COSTUME_SYSTEM\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_WEAPON_COSTUME_SYSTEM\",	0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_LVL115_ARMOR_EFFECT\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_LVL115_ARMOR_EFFECT\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_LVL115_ARMOR_EFFECT\",	0);\n"
			"#endif\n"
			"#ifdef ENABLE_SET_ATLAS_SCALE\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_SET_ATLAS_SCALE\", 1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_SET_ATLAS_SCALE\", 0);\n"
			"#endif\n\n\n"
			"#ifdef ENABLE_SLOT_WINDOW_EX\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_SLOT_WINDOW_EX\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_SLOT_WINDOW_EX\",	0);\n"
			"#endif\n\n"
			"#ifdef ENABLE_USE_COSTUME_ATTR\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_USE_COSTUME_ATTR\",	1);\n"
			"#else\n"
			"	PyModule_AddIntConstant(poModule, \"ENABLE_USE_COSTUME_ATTR\",	0);\n"
			"#endif\n\n"
			"	PyModule_AddIntConstant(poModule, \"USE_OPENID\",	0);\n"
			"	PyModule_AddIntConstant(poModule, \"OPENID_TEST\",	0);\n"
			"}\n")

matches = re.finditer(regex, test_str, re.MULTILINE)

for matchNum, match in enumerate(matches, start=1):

	print("Match {matchNum} was found at {start}-{end}: {match}".format(matchNum=matchNum, start=match.start(),
																		end=match.end(), match=match.group()))

	for groupNum in range(0, len(match.groups())):
		groupNum = groupNum + 1

		print("Group {groupNum} found at {start}-{end}: {group}".format(groupNum=groupNum, start=match.start(groupNum),
																		end=match.end(groupNum),
																		group=match.group(groupNum)))
